# dict.words

A Clojure library for working with the https://en.wikipedia.org/wiki/Words_(Unix)[words file] found on UNIX computers from https://clojure.org/[JVM Clojure] or http://planck-repl.org/[Planck].

    head /usr/share/dict/words

image:https://travis-ci.org/devstopfix/dict.words.svg?branch=master["Build Status", link="https://travis-ci.org/devstopfix/dict.words"]

# Build

## Build with https://leiningen.org/[Leiningen]

[source,bash]
----
git clone git@github.com:devstopfix/dict.words.git
cd dict.words
lein install
----

To run from http://planck-repl.org/[Planck REPL] you need to specify the http://planck-repl.org/source-dev.html[classpath to the build]:

[source,bash]
----
planck -c ~/.m2/repository/dict/words/dict.words/1.17.63/dict.words-1.17.63.jar
----

[source,clojure]
----
(filter (partial re-find #"^planck") words/words)
; ("planckian")
----

## Planck on Ubuntu

[source,bash]
----
sudo add-apt-repository ppa:mfikes/planck
sudo apt-get update

sudo apt-get install wget unzip planck wbritish wamerican

wget https://github.com/devstopfix/dict.words/archive/master.zip
unzip master
planck -c dict.words-master/src/
----


# Usage

## Words

The OSX dictionary is ASCII only, while Ubuntu wbritish contains French accents. Lazy seqs are provided of raw words and ASCII only:

[source,clojure]
----
(map last [words/words words/ascii-words])
; ("études" "zyzzogeton")
----

## Dinosaur names

[source,clojure]
----
(require '[dict.words :as words])

(first words/dinosaurs)
;=> "Aetosaurus"
----

## Hexadecimal words

Print words formed of https://en.wikipedia.org/wiki/Hexadecimal[Hexadecimal] characters:

[source,clojure]
----
(require '[dict.words.hex :refer [hex-words]])
(take 4 (shuffle hex-words))
; ("ABACA" "FACADE" "EFFACE" "DEFACE")
----

Or from the command line:

[source,bash]
----
planck -c src/ \
  -e "(require '[dict.words.hex :refer [hex-words]])" \
  -e '(doseq [w (sort hex-words)] (println (str "0x" w)))'

$ 0xABBA ...
----

### Hexadecimal leet

Words with digits that resemble letters:

[source,clojure]
----
(require '[dict.words.hex :refer [hex-words-leet]])
(take 4 (shuffle hex-words-leet))

; ("alf" "1eafed" "be11" "cede")
----

## REPL

To load or reload the words in the REPL:

[source,clojure]
----
(require '[dict.words :as words :reload true])
----

## Statistics

### Word length frequencies

[format="csv", options="header", cols=">,>"]
|===
Word length, Count
1, 26
2, 139
3, 1294
4, 4994
5, 9972
6, 17462
7, 23713
8, 29842
9, 32286
10, 30824
11, 25963
12, 20447
13, 14923
14, 9761
15, 5922
16, 3377
17, 1813
18, 842
19, 428
20, 198
21, 82
22, 41
23, 17
24, 5
|===

[source,clojure]
----
(require '[dict.words :as words])

(->> words/words
     (map count)
     (frequencies)
     (sort-by first))
----

## License

Copyright © 2017 Devstopfix

Distributed under the Eclipse Public License either version 1.0 or (at
your option) any later version.
